apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: maven-slave
  name: maven-slave
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: maven-slave:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    dockerfile: |-
      FROM docker.io/openshift/jenkins-slave-maven-centos7:v3.10
      USER root
      RUN yum -y install skopeo apb && yum clean all
      USER 1001
    type: Dockerfile
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: jenkins-slave-maven-centos7:v3.10
        namespace: openshift
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
  - github:
      secret: JfOtK2ihIY1OABAbOGGa
    type: GitHub
  - generic:
      secret: pba8aCj1NBh0ixi2Q5_H
    type: Generic
  - type: ConfigChange
  - imageChange: {}
    type: ImageChange
status:
  lastVersion: 0
