apiVersion: v1
items:
- kind: "BuildConfig"
  apiVersion: "v1"
  metadata:
    name: "mlbparks-pipeline"
  spec:
    source:
      type: "Git"
      git:
        uri: "https://github.com/honghuac/ocpadvdevhw/"
    strategy:
      type: "JenkinsPipeline"
      jenkinsPipelineStrategy:
        jenkinsfilePath: MLBParks/Jenkinsfile
      env:
        - GUID: "hchin"
          CLUSTER: "be9e.openshift.opentlc.com"
kind: List
metadata: []
